#!/bin/bash

openterminal="gnome-terminal"
opensource="gnome-terminal --tab -t src -- vim -p -S dev/.vimrc src/*.cpp"
opentest="gnome-terminal --tab -t test -- vim -p -S dev/.vimrc test/*.cpp"

if [ $# -eq 0 ]
then
    $openterminal
    $opensource
    $opentest
fi

while [[ $# -gt 0 ]]
do
    case $1 in
        test)
            $openmath
            ;;
        src)
            $openwave
            ;;
        make)
            $openterminal
            ;;
    esac
    shift 1
done

