#!/bin/bash

openterminal="gnome-terminal"
openws="gnome-terminal --tab -t src -- vim -p -S dev/.vimrc src/wstream/*.cpp"
opentest="gnome-terminal --tab -t test -- vim -p -S dev/.vimrc test/*.cpp"

if [ $# -eq 0 ]
then
    $openterminal
    $openws
    $opentest
fi

while [[ $# -gt 0 ]]
do
    case $1 in
        test)
            $opentest
            ;;
        ws)
            $openws
            ;;
        make)
            $openterminal
            ;;
    esac
    shift 1
done

